import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppHeader } from "@/components/organisms/AppHeader";
import { AppFooter } from "@/components/organisms/AppFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Page {
  title: string;
  to: string;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ページリストのデータをここで取得
  const pageList: Page[] = [
    { title: "案件を探す", to: "/" },
    { title: "ログイン", to: "/login" },
    { title: "新規登録", to: "/registration" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader pageList={pageList} />
        <div className="contents">{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
